spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xzmeasy
    password: Dev950210!
    url: jdbc:mysql://localhost:3306/es-search-house?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC